## Assignments

### 1. train test split from scratch

Create a function my_train_test_split() that takes ipnput X, y and fraction of train. And ouputs the list or tuple containing splits

In [1]:
import numpy as np

data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0], [9, 10, 1], [11, 12, 0]])
print('data:')
print(data)

def my_train_test_split(X_train, y_train, split_percent= 0.8):
    split = int(X.shape[0] * split_percent)

    # Split the data into training and testing sets
    X_train = data[:split, :-1]
    y_train = data[:split, -1]
    X_test = data[split:, :-1]
    y_test = data[split:, -1]

    return X_train, y_train, X_test, y_test

data:
[[ 1  2  0]
 [ 3  4  1]
 [ 5  6  1]
 [ 7  8  0]
 [ 9 10  1]
 [11 12  0]]


In [2]:
## TODO: Your function invocation goes here
X = data[:, :-1]  # Features
y = data[:, -1]   # Labels

train_frac = 0.8  # 80% for training, 20% for testing

X_train, y_train, X_test, y_test = my_train_test_split(X, y, train_frac)

# Printing the results
print("X_train:")
print(X_train)
print("y_train:")
print(y_train)
print("X_test:")
print(X_test)
print("y_test:")
print(y_test)

X_train:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
y_train:
[0 1 1 0]
X_test:
[[ 9 10]
 [11 12]]
y_test:
[1 0]


### 2. kNN from scratch

In [3]:
# KNN class that allows setting the number of neighbours and weight=uniform or distance
class KNN:
    def __init__(self, k = 7): #Fill this out
        self.k = k
        pass

    def fit(self, X_train, y_train): # What is missing in function definition?
        self.X_train = X_train
        self.y_train = y_train
        pass

    def euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def predict(self, X_test): # What is missing in function definition?
            y_pred = [self._predict(x) for x in X_test]
            return np.array(y_pred)
            pass
    
    def _predict(self, x):
        # Compute distances between x and all examples in the training set
        distances = [self.euclidean_distance(x, x_train) for x_train in self.X_train]
        
        # Sort by distance and return indices of the first k neighbors
        k_indices = np.argsort(distances)[:self.k]
        
        # Extract the labels of the k nearest neighbor training samples
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        
        # Return the most common class label
        most_common = np.bincount(k_nearest_labels).argmax()
        return most_common
    
    def evaluate(self, X_test, y_test):
         y_pred = self.predict(X_test)
         accuracy = sum(y_pred == y_test) / len(y_test)
         return accuracy
    

In [4]:
knn = KNN(k=7)
knn.fit(X_train, y_train)

In [5]:
y_pred = knn.predict(X_test)

In [6]:
print("Predicted Labels:")
print(y_pred)
print("True Labels:")
print(y_test)

Predicted Labels:
[0 0]
True Labels:
[1 0]


In [7]:
accuracies = []
ks = range(1,30)
for k in ks:
    knn.fit(X_train, y_train)
    accuracy = knn.evaluate(X_test, y_test)
    accuracies.append(accuracy)

print(accuracies)

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


In [8]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 50.00%


### 3. GridSearch from scratch

In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [10]:
data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0], [9, 10, 1], [11, 12, 0]])
print('data:')
print(data)

def my_train_test_split(X_train, y_train, split_percent= 0.8):
    split = int(X.shape[0] * split_percent)

    # Split the data into training and testing sets
    X_train = data[:split, :-1]
    y_train = data[:split, -1]
    X_test = data[split:, :-1]
    y_test = data[split:, -1]

    return X_train, y_train, X_test, y_test

data:
[[ 1  2  0]
 [ 3  4  1]
 [ 5  6  1]
 [ 7  8  0]
 [ 9 10  1]
 [11 12  0]]


In [11]:
X = data[:, :-1]  # Features
y = data[:, -1]   # Labels

train_frac = 0.8  # 80% for training, 20% for testing

X_train, y_train, X_test, y_test = my_train_test_split(X, y, train_frac)

# Printing the results
print("X_train:")
print(X_train)
print("y_train:")
print(y_train)
print("X_test:")
print(X_test)
print("y_test:")
print(y_test)

X_train:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
y_train:
[0 1 1 0]
X_test:
[[ 9 10]
 [11 12]]
y_test:
[1 0]


In [25]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(4, 2) (2, 2) (4,) (2,)


In [12]:
# knn = KNN()
# k_range = list(range(1,10, 2))
# dist_metrics = ['euclidian', 'manhattan']    
# k_range

In [13]:
# # param_grid = {('n_neighbors': [range(1,10,2)],  'dist': ['euclidian'])}
# para_grid = dict(n_neighbors = k_range)
# grid = GridSearchCV(knn, para_grid, cv=10, scoring= 'accuracy', return_train_score=False, verbose=1)
# grid_search = grid.fit(X_train, y_train)

In [14]:
# params = [{
#     'n_neighbors': [3, 5, 7, 9, 12,15,17],
#     'weights': ['uniform', 'distance'],
#     \
#     'metric': ['euclidean', 'manhattan']}]
# grid = GridSearchCV(knn, params, cv=10, scoring= 'accuracy', return_train_score=False, verbose=1)
# grid_search = grid.fit(X_train, y_train)

In [15]:
k_values = list(range(3, 8, 2))
weight_values = ['uniform', 'distance']

best_accuracy = 0
best_k = None
best_metric = None

In [16]:
def __init__(self, k=7, weight=['uniform', 'distance']):
        self.k = k
        self.weight = weight

In [26]:
from itertools import product
        
for k, weight in product(k_values, weight_values):
    knn = KNN(k = 5, weight = 'distance')
    knn.fit(X, y)
    accuracy = knn.evaluate(X, y)

    if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_k = k
            best_metric = weight

print(f"Best k: {best_k}")
print(f"Best weight: {best_metric}")
print(f"Best accuracy: {best_accuracy * 100:.2f}%")            



TypeError: __init__() got an unexpected keyword argument 'weight'

In [30]:
from sklearn import metrics

In [31]:
from itertools import product
def grid_search(params1, params2, x_train, y_train, x_test, y_test):
    hyper_params = list(product(params1, params2))
    max_score = 0
    best_params = None

    for i in hyper_params:
        knn = KNeighborsClassifier(n_neighbors=i[0], weights=i[1])
        knn.fit(x_train, y_train)
        y_pred = knn.predict(x_test)
        acc = metrics.accuracy_score(y_test, y_pred)
        if acc > max_score:
            max_score = acc
            best_params = (i[0], i[1])

    return best_params

In [ ]:
params1 = [1, 3, 5, 7]
params2 = ['uniform', 'distance'] 
best_params = grid_search(params1, params2, X_train, y_train, X_test, y_test)

print("Best Hyperparameters (k, weights):", best_params)

### 4. Integrate your custom code

1. Create a dataframe of iris dataset
2. Use your custom train test split function to split into train and test
3. Use your custom GridSearch on your customKNN class to identify the best k and best weight for iris dataset

In [34]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris  

In [45]:
iris = load_iris()
df_iris = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names'] + ['target'])

def my_train_test_split(X_train, y_train, train_frac= 0.8):
    split = int(X.shape[0] * train_frac)

    # Split the data into training and testing sets
    X_train = df_iris[:split, :-1]
    y_train = df_iris[:split, -1]
    X_test = df_iris[split:, :-1]
    y_test = df_iris[split:, -1]

    return X_train, y_train, X_test, y_test

In [46]:
X = df_iris.iloc[:, :-1].values
y = df_iris['target'].values
X_train, X_test, y_train, y_test = my_train_test_split(X, y)
train_frac = 0.8  # 80% for training, 20% for testing

X_train, y_train, X_test, y_test = my_train_test_split(X, y, train_frac)

# Printing the results
print("X_train:")
print(X_train)
print("y_train:")
print(y_train)
print("X_test:")
print(X_test)
print("y_test:")
print(y_test)

InvalidIndexError: (slice(None, 120, None), slice(None, -1, None))

In [47]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# Load the Iris dataset and create a DataFrame
iris = load_iris()
iris_df = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names'] + ['target'])

# Define your custom train-test split function
def my_train_test_split(X, y, train_fraction=0.8):
    data = np.column_stack((X, y))
    np.random.shuffle(data)
    split = int(train_fraction * data.shape[0])
    X_train, y_train = data[:split, :-1], data[:split, -1]
    X_test, y_test = data[split:, :-1], data[split:, -1]
    return X_train, X_test, y_train, y_test

# Split the dataset using your custom function
X = iris_df.iloc[:, :-1].values
y = iris_df['target'].values
X_train, X_test, y_train, y_test = my_train_test_split(X, y)

# Define your custom KNN class with weight parameter
class CustomKNN:
    def __init__(self, k=3, weight='uniform'):
        self.k = k
        self.weight = weight
        # Add other necessary methods for fitting and predicting

# Define hyperparameter values for grid search
k_values = [1, 3, 5, 7]  # Different values of k
weight_values = ['uniform', 'distance']  # Different weight options

# Initialize variables to store the best hyperparameters and accuracy
best_accuracy = 0
best_k = None
best_weight = None

# Perform grid search by iterating over hyperparameter combinations
for k, weight in product(k_values, weight_values):
    custom_knn = CustomKNN(k=k, weight=weight)
    # Train custom_knn using X_train and y_train
    # Predict using X_test
    # Calculate accuracy using y_test and store it in the 'accuracy' variable
    
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k
        best_weight = weight

# Print the best hyperparameters and accuracy
print(f"Best k: {best_k}")
print(f"Best weight: {best_weight}")
print(f"Best accuracy: {best_accuracy * 100:.2f}%")


Best k: 1
Best weight: uniform
Best accuracy: 50.00%
