## Assignments

### 1. train test split from scratch

Create a function my_train_test_split() that takes ipnput X, y and fraction of train. And ouputs the list or tuple containing splits

In [5]:
import numpy as np

data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0], [9, 10, 1], [11, 12, 0]])
print('data:')
print(data)

def my_train_test_split(X_train, y_train, split_percent= 0.8):
    split = int(X.shape[0] * split_percent)

    # Split the data into training and testing sets
    X_train = data[:split, :-1]
    y_train = data[:split, -1]
    X_test = data[split:, :-1]
    y_test = data[split:, -1]

    return X_train, y_train, X_test, y_test

data:
[[ 1  2  0]
 [ 3  4  1]
 [ 5  6  1]
 [ 7  8  0]
 [ 9 10  1]
 [11 12  0]]


In [6]:
## TODO: Your function invocation goes here
X = data[:, :-1]  # Features
y = data[:, -1]   # Labels

train_frac = 0.8  # 80% for training, 20% for testing

X_train, y_train, X_test, y_test = my_train_test_split(X, y, train_frac)

# Printing the results
print("X_train:")
print(X_train)
print("y_train:")
print(y_train)
print("X_test:")
print(X_test)
print("y_test:")
print(y_test)

X_train:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
y_train:
[0 1 1 0]
X_test:
[[ 9 10]
 [11 12]]
y_test:
[1 0]


### 2. kNN from scratch

In [7]:
# KNN class that allows setting the number of neighbours and weight=uniform or distance
class KNN:
    def __init__(self, k = 7): #Fill this out
        self.k = k
        pass

    def fit(self, X_train, y_train): # What is missing in function definition?
        self.X_train = X_train
        self.y_train = y_train
        pass

    def euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def predict(self, X_test): # What is missing in function definition?
            y_pred = [self._predict(x) for x in X_test]
            return np.array(y_pred)
            pass
    
    def _predict(self, x):
        # Compute distances between x and all examples in the training set
        distances = [self.euclidean_distance(x, x_train) for x_train in self.X_train]
        
        # Sort by distance and return indices of the first k neighbors
        k_indices = np.argsort(distances)[:self.k]
        
        # Extract the labels of the k nearest neighbor training samples
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        
        # Return the most common class label
        most_common = np.bincount(k_nearest_labels).argmax()
        return most_common
    
    def evaluate(self, X_test, y_test):
         y_pred = self.predict(X_test)
         accuracy = sum(y_pred == y_test) / len(y_test)
         return accuracy
    

In [8]:
knn = KNN(k=7)
knn.fit(X_train, y_train)

In [9]:
y_pred = knn.predict(X_test)

In [10]:
print("Predicted Labels:")
print(y_pred)
print("True Labels:")
print(y_test)

Predicted Labels:
[0 0]
True Labels:
[1 0]


In [11]:
accuracies = []
ks = range(1,30)
for k in ks:
    knn.fit(X_train, y_train)
    accuracy = knn.evaluate(X_test, y_test)
    accuracies.append(accuracy)

print(accuracies)

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


In [12]:
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 50.00%


### 3. GridSearch from scratch

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV

In [14]:
data = np.array([[1, 2, 0], [3, 4, 1], [5, 6, 1], [7, 8, 0], [9, 10, 1], [11, 12, 0]])
print('data:')
print(data)

def my_train_test_split(X_train, y_train, split_percent= 0.8):
    split = int(X.shape[0] * split_percent)

    # Split the data into training and testing sets
    X_train = data[:split, :-1]
    y_train = data[:split, -1]
    X_test = data[split:, :-1]
    y_test = data[split:, -1]

    return X_train, y_train, X_test, y_test

data:
[[ 1  2  0]
 [ 3  4  1]
 [ 5  6  1]
 [ 7  8  0]
 [ 9 10  1]
 [11 12  0]]


In [15]:
X = data[:, :-1]  # Features
y = data[:, -1]   # Labels

train_frac = 0.8  # 80% for training, 20% for testing

X_train, y_train, X_test, y_test = my_train_test_split(X, y, train_frac)

# Printing the results
print("X_train:")
print(X_train)
print("y_train:")
print(y_train)
print("X_test:")
print(X_test)
print("y_test:")
print(y_test)

X_train:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
y_train:
[0 1 1 0]
X_test:
[[ 9 10]
 [11 12]]
y_test:
[1 0]


In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [17]:
knn = KNN()
k_range = list(range(1,10, 2))
k_range

[1, 3, 5, 7, 9]

In [19]:
# param_grid = {('n_neighbors': [range(1,10,2)],  'dist': ['euclidian'])}
para_grid = dict(n_neighbors = k_range)
grid = GridSearchCV(knn, para_grid, cv=10, scoring= 'accuracy', return_train_score=False, verbose=1)
grid_search = grid.fit(X_train, y_train)

TypeError: Cannot clone object '<__main__.KNN object at 0x0000024ECECC8820>' (type <class '__main__.KNN'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' method.